const list = {
    remenkecheng_title: [
        {
            'title': '热门课程',
            'a': '查看更多',
            'dt': '实战课排行榜规则',
            'dd': '根据近30天购买人数由高到低进行推荐',
            'dt1': '免费课排行榜规则',
            'dd1': '根据近30天观看人数由高到低进行推荐',
        }
    ],
    remenkecheng: [
        {
            'id': '1',
            "remenkecheng_title": "实战课程",
            "remengkecheng_content": [
                {
                    'phb_biaoqian': '',
                    'phb_label2': '计算机网络',
                    'phb_label': 'Linux',
                    'phb_title': '编程必备基础 计算机组成原理+操作系统+计算机网络',
                    'phb_info1': '中级',
                    'phb_info2': '2010',
                    'phb_info3': '612人评价',
                    'phb_price': '￥236.00 ',
                    'phb_desc': '',
                    'phb_zhpf': '综合评分',
                    'phb_pf': '10.00',
                    'phb_pj': '612人评价',
                    'phb_info4': '内容实用',
                    'phb_info_1': '10.00',
                    'phb_info5': '通俗易懂',
                    'phb_info_2': '10.00',
                    'phb_info6': '逻辑清晰',
                    'phb_info_3': '10.00',
                    'phb_imgsrc': "http://img1.mukewang.com/szimg/5d1032ab08719e0906000338-360-202.jpg",
                },

                {
                    'phb_biaoqian': '',
                    'phb_label2': '算法与数据结构',
                    'phb_label': 'Java',
                    'phb_title': '剑指Java面试-Offer直通车',
                    'phb_info1': '中级',
                    'phb_info2': '4643',
                    'phb_info3': '1596人评价',
                    'phb_price': '￥299.00',
                    'phb_desc': '',
                    'phb_zhpf': '综合评分',
                    'phb_pf': '10.00',
                    'phb_pj': '1596人评价',
                    'phb_info4': '内容实用',
                    'phb_info_1': '10.00',
                    'phb_info5': '通俗易懂',
                    'phb_info_2': '10.00',
                    'phb_info6': '逻辑清晰',
                    'phb_info_3': '10.00',
                    'phb_imgsrc': "http://img4.mukewang.com/szimg/5c18d2d8000141c506000338-360-202.jpg",
                },
                {
                    'phb_biaoqian': '升级',
                    'phb_label': 'Html5',
                    'phb_label2': '小程序',
                    'phb_title': '微信小程序入门与实战 常用组件API开发技巧项目实战',
                    'phb_info1': '初级',
                    'phb_info2': '18812',
                    'phb_info3': '3882人评价',
                    'phb_price': '￥149.00 ',
                    'phb_desc': '',
                    'phb_zhpf': '综合评分',
                    'phb_pf': '9.99',
                    'phb_pj': '3882人评价',
                    'phb_info4': '内容实用',
                    'phb_info_1': '9.98',
                    'phb_info5': '通俗易懂',
                    'phb_info_2': '10.00',
                    'phb_info6': '逻辑清晰',
                    'phb_info_3': '10.00',
                    'phb_imgsrc': "https://img2.mukewang.com/szimg/5c0493ce000126b106000338-360-202.jpg",
                },
                {
                    'phb_biaoqian': '',
                    'phb_label2': '',
                    'phb_label': 'Java',
                    'phb_title': 'Java并发编程精讲',
                    'phb_info1': '中级',
                    'phb_info2': '913',
                    'phb_info3': '226人评价',
                    'phb_price': '￥348.00 ',
                    'phb_desc': '',
                    'phb_zhpf': '综合评分',
                    'phb_pf': '10.00',
                    'phb_pj': '226人评价',
                    'phb_info4': '内容实用',
                    'phb_info_1': '10.00',
                    'phb_info5': '通俗易懂',
                    'phb_info_2': '10.00',
                    'phb_info6': '逻辑清晰',
                    'phb_info_3': '10.00',
                    'phb_imgsrc': "https://img4.mukewang.com/szimg/5d4ceaef09c3cb6612000676-360-202.png",
                },

                {
                    'phb_biaoqian': '',
                    'phb_label': 'Python',
                    'phb_label2': '',
                    'phb_title': '全面系统python3入门+进阶课程 小白也能听懂',
                    'phb_info1': '初级',
                    'phb_info2': '9769',
                    'phb_info3': '3066人评价',
                    'phb_price': '￥366.00',
                    'phb_desc': '',
                    'phb_zhpf': '综合评分',
                    'phb_pf': '10.00',
                    'phb_pj': '3066人评价',
                    'phb_info4': '内容实用',
                    'phb_info_1': '10.00',
                    'phb_info5': '通俗易懂',
                    'phb_info_2': '10.00',
                    'phb_info6': '逻辑清晰',
                    'phb_info_3': '10.00',
                    'phb_imgsrc': "https://img4.mukewang.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                },

                {
                    'phb_biaoqian': '',
                    'phb_label': 'C++',
                    'phb_label2': '',
                    'phb_title': '百万级高并发WebRTC流媒体服务器设计与开发',
                    'phb_info1': '高级',
                    'phb_info2': '286',
                    'phb_info3': '9人评价',
                    'phb_price': '￥286.00 ',
                    'phb_desc': '',
                    'phb_zhpf': '综合评分',
                    'phb_pf': '10.00',
                    'phb_pj': '9人评价',
                    'phb_info4': '内容实用',
                    'phb_info_1': '10.00',
                    'phb_info5': '通俗易懂',
                    'phb_info_2': '10.00',
                    'phb_info6': '逻辑清晰',
                    'phb_info_3': '10.00',
                    'phb_imgsrc': "https://img3.mukewang.com/szimg/5d843d26092f474812000676-360-202.png",
                },

                {
                    'phb_biaoqian': '',
                    'phb_label2': '算法',
                    'phb_label': '数据结构',
                    'phb_title': '玩转算法系列--数据结构精讲 更适合0算法基础入门到进阶（java版）',
                    'phb_info1': '中级',
                    'phb_info2': '4810',
                    'phb_info3': '1701人评价',
                    'phb_price': '￥299.00',
                    'phb_desc': '',
                    'phb_zhpf': '综合评分',
                    'phb_pf': '10.00',
                    'phb_pj': '1701人评价',
                    'phb_info4': '内容实用',
                    'phb_info_1': '10.00',
                    'phb_info5': '通俗易懂',
                    'phb_info_2': '10.00',
                    'phb_info6': '逻辑清晰',
                    'phb_info_3': '10.00',
                    'phb_imgsrc': "https://img4.mukewang.com/szimg/5ad05dc00001eae705400300-360-202.jpg",
                },

                {
                    'phb_biaoqian': '',
                    'phb_label2': '',
                    'phb_label': 'Vue.js',
                    'phb_title': 'Vue2.5开发去哪儿网App 从零基础入门到实战项目',
                    'phb_info1': '中级',
                    'phb_info2': '6856',
                    'phb_info3': '3100人评价',
                    'phb_price': '￥266.00',
                    'phb_desc': '',
                    'phb_zhpf': '综合评分',
                    'phb_pf': '10.00',
                    'phb_pj': '3100人评价',
                    'phb_info4': '内容实用',
                    'phb_info_1': '10.00',
                    'phb_info5': '通俗易懂',
                    'phb_info_2': '10.00',
                    'phb_info6': '逻辑清晰',
                    'phb_info_3': '10.00',
                    'phb_imgsrc': "https://img2.mukewang.com/szimg/5ac2dfe100014a9005400300-360-202.jpg",
                },
            ],
        },
        {
            'id': '2',
            "remenkecheng_title": "免费课程",
            "remengkecheng_content": [
                {
                    'phb_biaoqian': '',
                    'phb_label2': '',
                    'phb_label': 'C',
                    'phb_title': 'C语言入门',
                    'phb_info1': '入门',
                    'phb_info2': '781387',
                    'phb_info3': '',
                    'phb_price': '',
                    'phb_desc': 'C语言入门视频教程，带你进入编程世界的必修课-C语言',
                    'phb_imgsrc': "http://img4.mukewang.com/574669dc0001993606000338-360-202.jpg",
                },

                {
                    'phb_biaoqian': '',
                    'phb_label2': '',
                    'phb_label': 'Python',
                    'phb_title': '初识Python',
                    'phb_info1': '入门',
                    'phb_info2': '699615',
                    'phb_info3': '',
                    'phb_price': '',
                    'phb_desc': '学python入门视频教程，让你快速入门并能编写简单的Python程序',
                    'phb_imgsrc': "https://img4.mukewang.com/540e57300001d6d906000338-360-202.jpg",
                },
                {
                    'phb_biaoqian': '',
                    'phb_label': 'Java',
                    'phb_label2': '',
                    'phb_title': 'Java入门第一季',
                    'phb_info1': '入门',
                    'phb_info2': '1023580',
                    'phb_info3': '',
                    'phb_price': '',
                    'phb_desc': '本教程从Java环境搭建、工具使用、基础语法开始，带你入门',
                    'phb_imgsrc': "https://img4.mukewang.com/57035ff200014b8a06000338-360-202.jpg",
                },
                {
                    'phb_biaoqian': '',
                    'phb_label2': '',
                    'phb_label': 'HTML/CSS',
                    'phb_title': '初识HTML+CSS',
                    'phb_info1': '入门',
                    'phb_info2': '1079237',
                    'phb_info3': '',
                    'phb_price': '',
                    'phb_desc': 'HTML+CSS基础教程8小时带领大家步步深入学习标签用法和意义',
                    'phb_imgsrc': "https://img.mukewang.com/529dc3380001379906000338-360-202.jpg",
                },

                {
                    'phb_biaoqian': '',
                    'phb_label': 'JavaScript',
                    'phb_label2': '',
                    'phb_title': 'JavaScript入门篇',
                    'phb_info1': '入门',
                    'phb_info2': '670310',
                    'phb_info3': '',
                    'phb_price': '',
                    'phb_desc': 'JavaScript做为一名Web工程师的必备技术，本教程让您快速入门',
                    'phb_imgsrc': "https://img3.mukewang.com/53e1d0470001ad1e06000338-360-202.jpg",
                },

                {
                    'phb_biaoqian': '',
                    'phb_label': '区块链',
                    'phb_label2': '以太坊',
                    'phb_title': '区块链技术核心概念与原理讲解',
                    'phb_info1': '入门',
                    'phb_info2': '48925',
                    'phb_info3': '',
                    'phb_price': '',
                    'phb_desc': '登链科技首席技术官(Tiny熊），为你讲解区块链技术核心概念与原理',
                    'phb_imgsrc': "https://img3.mukewang.com/5ae3e5b80001818c06000338-360-202.jpg",
                },

                {
                    'phb_biaoqian': '',
                    'phb_label2': '',
                    'phb_label': '设计工具',
                    'phb_title': 'PS入门教程——新手过招',
                    'phb_info1': '入门',
                    'phb_info2': '587037',
                    'phb_info3': '',
                    'phb_price': '',
                    'phb_desc': '慕课网推出的PS入门教程，PS入门学习必备课程，带你轻松入门',
                    'phb_imgsrc': "https://img2.mukewang.com/53a28e960001311b06000338-360-202.jpg",
                },

                {
                    'phb_biaoqian': '',
                    'phb_label2': '',
                    'phb_label': 'Vue.js',
                    'phb_title': 'vue-cli全集',
                    'phb_info1': '入门',
                    'phb_info2': '8735',
                    'phb_info3': '',
                    'phb_price': '',
                    'phb_desc': '手把手带你学习从项目创建到项目升级，完美契合企业需求',
                    'phb_imgsrc': "https://img.mukewang.com/5d650d3608853f3b06000338-360-202.jpg",
                },
            ],
        }

    ],
}
export default list