const list = {
    xingshanghaoke: [
        {
            "img_src": "https://img4.mukewang.com/szimg/5db7fa4f09a2b64312000676-360-202.png",
            "course_name": "再学JavaScript  ES(6-10)全版本语法大全",
            "course_jibie": "初级",
            "course_shuliang": "109",
            "course_pingjia": "4人评价",
            "course_card_info_price": "￥299.00",
            "course_stat": "新课",
            "course_stat2": "new",
            "course_label": "JavaScript",
            "course_label2": "Vue.js",
            'phb_zhpf': '综合评分',
            'phb_pf': '10.00',
            'phb_pj': '4人评价',
            'phb_info4': '内容实用',
            'phb_info_1': '9.98',
            'phb_info5': '通俗易懂',
            'phb_info_2': '10.00',
            'phb_info6': '逻辑清晰',
            'phb_info_3': '10.00',
        },
        {
            "img_src": "https://img3.sycdn.imooc.com/szimg/5db294a509c673af12000676-360-202.png",
            "course_name": "聚焦市场开发热门技术 手把手带你开发商业级社交App",
            "course_jibie": "中级",
            "course_shuliang": "54",
            "course_pingjia": "6人评价",
            "course_card_info_price": "￥348.00",
            "course_stat": "新课",
            "course_stat2": "new",
            "course_label": "Android",
            "course_label2": "",
            'phb_zhpf': '综合评分',
            'phb_pf': '10.00',
            'phb_pj': '6人评价',
            'phb_info4': '内容实用',
            'phb_info_1': '9.98',
            'phb_info5': '通俗易懂',
            'phb_info_2': '10.00',
            'phb_info6': '逻辑清晰',
            'phb_info_3': '10.00',
        },
        {
            "img_src": "https://img4.sycdn.imooc.com/szimg/5d14215f08545a6b06000338-360-202.jpg",
            "course_name": "Spring Cloud Alibaba微服务从入门到进阶",
            "course_jibie": "高级",
            "course_shuliang": "741",
            "course_pingjia": "327人评价",
            "course_card_info_price": "￥399.00",
            "course_stat": "",
            "course_stat2": "new",
            "course_label": "SpringBoot",
            "course_label2": "Spring Cloud",
            'phb_zhpf': '综合评分',
            'phb_pf': '10.00',
            'phb_pj': '327人评价',
            'phb_info4': '内容实用',
            'phb_info_1': '9.98',
            'phb_info5': '通俗易懂',
            'phb_info_2': '10.00',
            'phb_info6': '逻辑清晰',
            'phb_info_3': '10.00',
        },
        {
            "img_src": "https://img1.sycdn.imooc.com/szimg/5da13cab09466e9105400306-360-202.png",
            "course_name": "Node.js+Koa2框架生态实战 - 从零模拟新浪微博",
            "course_jibie": "中级",
            "course_shuliang": "138",
            "course_pingjia": "7人评价",
            "course_card_info_price": "￥366.00",
            "course_stat": "新课",
            "course_stat2": "new",
            "course_label": "JavaScript",
            "course_label2": "Node.js",
            'phb_zhpf': '综合评分',
            'phb_pf': '10.00',
            'phb_pj': '7人评价',
            'phb_info4': '内容实用',
            'phb_info_1': '9.98',
            'phb_info5': '通俗易懂',
            'phb_info_2': '10.00',
            'phb_info6': '逻辑清晰',
            'phb_info_3': '10.00',
        },
        {
            "img_src": "https://img3.sycdn.imooc.com/szimg/5d5377660922e54c12000676-360-202.png",
            "course_name": "微信小程序云开发-从0打造云音乐全栈小程序",
            "course_jibie": "中级",
            "course_shuliang": "422",
            "course_pingjia": "88人评价",
            "course_card_info_price": "￥346.00",
            "course_stat": "",
            "course_stat2": "new",
            "course_label": "Node.js",
            "course_label2": "小程序",
            'phb_zhpf': '综合评分',
            'phb_pf': '10.00',
            'phb_pj': '88人评价',
            'phb_info4': '内容实用',
            'phb_info_1': '9.98',
            'phb_info5': '通俗易懂',
            'phb_info_2': '10.00',
            'phb_info6': '逻辑清晰',
            'phb_info_3': '10.00',
        },
        {
            "img_src": "https://img1.sycdn.imooc.com/szimg/5af2a67500016b9905400300-360-202.jpg",
            "course_name": "区块链入门与去中心化应用实战",
            "course_jibie": "初级",
            "course_shuliang": "913",
            "course_pingjia": "104人评价",
            "course_card_info_price": "￥199.00",
            "course_stat": "",
            "course_stat2": "new",
            "course_label": "区块链",
            "course_label2": "",
            'phb_zhpf': '综合评分',
            'phb_pf': '10.00',
            'phb_pj': '104人评价',
            'phb_info4': '内容实用',
            'phb_info_1': '9.98',
            'phb_info5': '通俗易懂',
            'phb_info_2': '10.00',
            'phb_info6': '逻辑清晰',
            'phb_info_3': '10.00',
        },
        {
            "img_src": "https://img1.sycdn.imooc.com/szimg/5d9c62fb0907ccf012000676-360-202.png",
            "course_name": "ElasticSearch+Spark  构建高匹配度搜索服务+千人千面推荐系统",
            "course_jibie": "中级",
            "course_shuliang": "227",
            "course_pingjia": "6人评价",
            "course_card_info_price": "￥348.00",
            "course_stat": "新课",
            "course_stat2": "new",
            "course_label": "Java",
            "course_label2": "机器学习",
            'phb_zhpf': '综合评分',
            'phb_pf': '10.00',
            'phb_pj': '6人评价',
            'phb_info4': '内容实用',
            'phb_info_1': '9.98',
            'phb_info5': '通俗易懂',
            'phb_info_2': '10.00',
            'phb_info6': '逻辑清晰',
            'phb_info_3': '10.00',
        },
        {
            "img_src": "https://img4.sycdn.imooc.com/szimg/5d843d26092f474812000676-360-202.png",
            "course_name": "百万级高并发WebRTC流媒体服务器设计与开发",
            "course_jibie": "高级",
            "course_shuliang": "271",
            "course_pingjia": "9人评价",
            "course_card_info_price": "￥366.00",
            "course_stat": "",
            "course_stat2": "new",
            "course_label": "C++",
            "course_label2": "",
            'phb_zhpf': '综合评分',
            'phb_pf': '10.00',
            'phb_pj': '9人评价',
            'phb_info4': '内容实用',
            'phb_info_1': '9.98',
            'phb_info5': '通俗易懂',
            'phb_info_2': '10.00',
            'phb_info6': '逻辑清晰',
            'phb_info_3': '10.00',
        },
    ]
}
export default list